apiVersion: v2
name: azimuth-caas-operator
description: Helm chart for deploying the Azimuth Cluster-as-a-Service operator.
type: application
# The version and appVersion are set by the CI script
version: 0.1.0
appVersion: "main"
