# The image to use for the ARA deployment
image:
  # This is a mirror of quay.io/recordsansible/ara-api that is mirrored
  # and tagged for each operator version that is built
  # This is because the quay.io repo only provides latest tags
  repository: ghcr.io/azimuth-cloud/ara-api
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion

imagePullSecrets: []

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true
  # Because the container user is root, we need to pick a non-root UID
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

# Container-level security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# The liveness probe for ARA containers
livenessProbe:
  httpGet:
    path: /api/v1/
    port: http
    httpHeaders:
      - name: Host
        value: localhost
# The readiness probe for ARA containers
readinessProbe:
  httpGet:
    path: /api/v1/
    port: http
    httpHeaders:
      - name: Host
        value: localhost

# Resource requests and limits for the containers
resources: {}

# Node selector for ARA pods
nodeSelector: {}

# Affinity rules for ARA pods
affinity: {}

# Tolerations for ARA pods
tolerations: []

# Settings for persistence for ARA
persistence:
  # Indicates whether persistence should be enabled
  enabled: true
  # If set, use an existing PVC instead of creating one
  existingClaim:
  # The access modes for the PVC
  accessModes:
    - ReadWriteOnce
  # The storage class to use for the PVC
  # If not given, the default storage class is used
  # If set to "-" then storageClassName is set to "", disabling dynamic provisioning
  storageClass:
  # The volume binding mode for the created PVC
  # If not given, the default volume binding mode for the storage class is used
  volumeBindingMode:
  # The size of the PVC
  size: 8Gi
  # The label selector to use to filter eligible PVs
  # Useful if PVs have been provisioned in advance
  selector:
  # The name of a specific PV to bind
  # Useful if you want to bind to a specific pre-provisioned PV
  volumeName:
