kind: Deployment
apiVersion: apps/v1
metadata:
  name: azimuth-ara
  labels:
    app: ara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ara
  template:
    metadata:
      labels:
        app: ara
    spec:
      containers:
        - name: ara-api
          image:  quay.io/recordsansible/ara-api:latest
          ports:
            - containerPort: 8000
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /opt/ara
          env:
          - name: ARA_ALLOWED_HOSTS
            value: '["127.0.0.1", "localhost", "::1", "azimuth-ara.{{ .Release.Namespace }}"]'
          - name: ARA_IGNORED_FACTS
            value: '["ansible_env_skip"]'
      volumes:
        # TODO: PVC!!
        - name: data
          emptyDir: {}
