apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth-caas-operator.fullname" . }}
  labels:
    {{- include "azimuth-caas-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "azimuth-caas-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "azimuth-caas-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "azimuth-caas-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "CONSUL_HTTP_ADDR"
            # TODO - we a variable for this
            value: "http://consul-server.{{ .Release.Namespace }}:8500"
          - name: "ARA_API_SERVER"
            value: "http://azimuth-ara.{{ .Release.Namespace }}:8000"
          - name: "ANSIBLE_RUNNER_IMAGE"
            value: "ghcr.io/stackhpc/azimuth-caas-operator-ar:v0.1.0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
