{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azimuth-caas-operator.serviceAccountName" . }}
  labels:
    {{- include "azimuth-caas-operator.labels" . | nindent 4 }}
{{- end }}
