apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azimuth-caas-operator.fullname" . }}:controller
  labels: {{ include "azimuth-caas-operator.labels" . | nindent 4 }}
rules:
  # Required by kopf
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
  # Required by azimuth-caas
  - apiGroups: ["caas.azimuth.stackhpc.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - scheduling.azimuth.stackhpc.com
    resources:
      - leases
    verbs:
      - list
      - get
      - delete
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - configmaps
      - persistentvolumeclaims
      - pods
      - pods/log
      - secrets
      - serviceaccounts
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - rolebindings
    verbs: ["get", "list", "create", "update", "patch"]
  # Required so that the CaaS operator can grant permissions on leases for the TF plugin
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, create, update]
