apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azimuth-caas-operator.fullname" . }}
  labels: {{ include "azimuth-caas-operator.labels" . | nindent 4 }}
spec:
  # Allow only one replica at once with the recreate strategy in order to avoid races
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "azimuth-caas-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "azimuth-caas-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "azimuth-caas-operator.fullname" . }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.config.consulUrl }}
            - name: CONSUL_HTTP_ADDR
              value: {{ tpl .Values.config.consulUrl . | quote }}
            {{- end }}
            - name: ARA_API_SERVER
              value: {{ tpl .Values.config.araUrl . | quote }}
            - name: ANSIBLE_RUNNER_IMAGE_REPO
              value: {{ quote .Values.config.ansibleRunnerImage.repository }}
            - name: ANSIBLE_RUNNER_IMAGE_TAG
              value: {{ default .Chart.AppVersion .Values.config.ansibleRunnerImage.tag | quote }}
            - name: GLOBAL_EXTRAVARS_SECRET
              value: {{
                include "azimuth-caas-operator.fullname" . |
                  printf "%s/%s-extravars" .Release.Namespace |
                  quote
              }}
            - name: ANSIBLE_RUNNER_CLUSTER_ROLE
              value: {{ include "azimuth-caas-operator.fullname" . }}:tfstate
            {{- if .Values.trustBundle }}
            - name: TRUST_BUNDLE_CONFIGMAP
              value: {{ include "azimuth-caas-operator.fullname" . }}-trust-bundle
            {{- end }}
            - name: SELF_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEASE_CHECK_INTERVAL_SECONDS
              value: {{ .Values.config.leaseCheckIntervalSeconds | quote }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.trustBundle }}
            - name: trust-bundle
              mountPath: /etc/ssl/certs
              readOnly: true
            {{- end }}
            - name: tmp
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.trustBundle }}
        - name: trust-bundle
          configMap:
            name: {{ include "azimuth-caas-operator.fullname" . }}-trust-bundle
        {{- end }}
        - name: tmp
          emptyDir: {}
