# Config for the operator
config:
  # The URL for Consul
  consulUrl: "{{ fail \"config.consulUrl is required\" }}"
  # The URL for ARA
  araUrl: "{{ printf \"http://%s-ara.%s:8000\" .Release.Name .Release.Namespace }}"
  # The image for ansible runner
  ansibleRunnerImage:
    repository: ghcr.io/stackhpc/azimuth-caas-operator-ee
    tag: ""  # Defaults to appVersion

# The operator image to use
image:
  repository: ghcr.io/stackhpc/azimuth-caas-operator
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to appVersion

imagePullSecrets: []

# Pod-level security context
podSecurityContext:
  runAsNonRoot: true

# Container-level security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

# Resource requests and limits for the containers
resources: {}

# Node selector for operator pods
nodeSelector: {}

# Affinity rules for operator pods
affinity: {}

# Tolerations for operator pods
tolerations: []

# Settings for kube-state-metrics
metrics:
  enabled: false
  # Configuration for the dashboard
  dashboard:
    enabled: false
    labels:
      grafana_dashboard: "1"
  prometheus:
    rules:
      enabled: true
    monitor:
      enabled: true
      honorLabels: true
  # Disable all the default collectors
  collectors: []
  # Allow kube-state-metrics read-only access to our CRDs
  rbac:
    create: true
    extraRules:
      - apiGroups:
          - caas.azimuth.stackhpc.com
        resources:
          - clusters
          - clustertypes
        verbs:
          - list
          - watch
          - get
  # Configure kube-state-metrics to report only on our custom resources
  extraArgs:
    - --custom-resource-state-only=true
  customResourceState:
    enabled: true
    config:
      kind: CustomResourceStateMetrics
      spec:
        resources:
          - groupVersionKind:
              group: caas.azimuth.stackhpc.com
              version: v1alpha1
              kind: Clusters
            metricNamePrefix: azimuth_caas_clusters
            labelsFromPath:
              cluster_namespace: [metadata, namespace]
              cluster_name: [metadata, name]
              cluster_type_name: [spec, clusterTypeName]
              cluster_type_version: [spec, clusterTypeVersion]
            metrics:
              - name: phase
                help: "Cluster phase"
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      phase: [status, phase]

          - groupVersionKind:
              group: caas.azimuth.stackhpc.com
              version: v1alpha1
              kind: ClusterTypes
            metricNamePrefix: azimuth_caas_clustertypes
            labelsFromPath:
              cluster_type_namespace: [metadata, namespace]
              cluster_type_name: [metadata, name]
              cluster_type_version: [metadata, resourceVersion]
            metrics:
              - name: phase
                help: "Cluster phase"
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      phase: [status, phase]
