apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ara.fullname" . }}
  labels: {{ include "ara.labels" . | nindent 4 }}
spec:
  # Because we use a RWO PVC for sqlite, we can only have one replica at a time
  # Also, we must use the recreate strategy in order to avoid races for the PVC
  # If we want to use multiple replicas, we need to configure ARA to use an external DB
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "ara.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "ara.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ara
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (default .Chart.AppVersion .Values.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ARA_ALLOWED_HOSTS
              # Allow any hosts for ARA
              # We rely on whatever is providing ingress to validate the host
              value: '["*"]'
            - name: ARA_IGNORED_FACTS
              value: '["ansible_env_skip"]'
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/ara
            - name: tmp
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "ara.fullname" . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
