apiVersion: v1
kind: Service
metadata:
  name: {{ include "ara.fullname" . }}
  labels: {{ include "ara.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector: {{ include "ara.selectorLabels" . | nindent 4 }}
