{
 "title": "Azimuth / CaaS Clusters",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\"}) by (cluster_namespace, cluster_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\"}) by (cluster_namespace, cluster_name)) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\"}) by (cluster_namespace, cluster_name)) by (cluster_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\",phase=\"Ready\"}) by (cluster_namespace, cluster_name)) by (cluster_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\",phase=\"Failed\"}) by (cluster_namespace, cluster_name)) by (cluster_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cluster Types",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clustertypes_phase{}) by (cluster_type_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clusters by cluster type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clusters_phase{cluster_type_name=~\".+\"}) by (cluster_namespace, cluster_name)) by (cluster_type_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable templates",
   "type": "stat",
   "description": "Number of templates that have not been synced for more than 24 hours",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, azimuth_caas_clustertypes_phase{phase!=\"Available\"}) by (cluster_type_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster type details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cluster Types",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(1, azimuth_caas_clustertypes_phase) by(cluster_type_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Clusters",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(1, azimuth_caas_clusters_phase) by(cluster_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}