---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: Cluster
metadata:
  name: test1
spec:
  clusterTypeName: azimuth-sample-appliance
  cloudCredentialsSecretName: my-workstation-cloud-credentials
  extraVars:
    foo: bar
