---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "azimuth-sample-appliance"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-sample-appliance/ff97632f6d53b801d4149d1c031c1d17e50986ca/ui-meta/sample-appliance.yml"
  gitUrl: "https://github.com/stackhpc/azimuth-sample-appliance.git"
  gitVersion: "bf6d8f644736a18783763d9ebded86204ad7f7be"
  playbook: "/sample-appliance.yml"
  extraVars:
    cluster_image: "f7e6408b-a9b8-4ba2-a4c1-e19f61bebe7e"
    #??cluster_image: "136d3959-c59b-4016-a4e7-2ee2ed25d490"
