---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "quick-test"
spec:
  # TODO - fix up this url to something more useful?
  # uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-sample-appliance/ff97632f6d53b801d4149d1c031c1d17e50986ca/ui-meta/sample-appliance.yml"
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/caas-workstation/953c9b1098f4ebffc40e8dd5eb984affcc4d3fc4/ui-meta/workstation.yml"
  gitUrl: "https://github.com/ansible/ansible-runner"
  gitVersion: "devel"
  playbook: "demo/project/test.yml"
---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "azimuth-sample-appliance"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-sample-appliance/ff97632f6d53b801d4149d1c031c1d17e50986ca/ui-meta/sample-appliance.yml"
  gitUrl: "https://github.com/stackhpc/azimuth-sample-appliance.git"
  gitVersion: "bf6d8f644736a18783763d9ebded86204ad7f7be"
  playbook: "sample-appliance.yml"
  extraVars:
    #?cluster_image: "f7e6408b-a9b8-4ba2-a4c1-e19f61bebe7e"
    cluster_image: "8be8c170-cd91-4c05-b2eb-269bfd68316d"
---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "workstation"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/caas-workstation/953c9b1098f4ebffc40e8dd5eb984affcc4d3fc4/ui-meta/workstation.yml"
  gitUrl: "https://github.com/stackhpc/caas-workstation.git"
  gitVersion: "6728851434a27afa0370f9c12fe509d897c897ba"
  playbook: "workstation.yml"
  extraVars:
    cluster_image: "6c30d015-6193-4479-b962-653a1a18d622"
