---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "quick-test"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-caas-operator/d977b04df85d7492ba726daf249709731130e6cf/tools/ui_meta_quick_test.yaml"
  gitUrl: "https://github.com/ansible/ansible-runner"
  gitVersion: "devel"
  playbook: "demo/project/test.yml"
  extraVars:
    foo: "bar"
