---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "quick-test"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-caas-operator/31592b8b5a8852cbf0cd12a41628063ac8e82ae3/tools/ui_meta_quick_test.yaml"
  gitUrl: "https://github.com/JohnGarbutt/ansible-runner"
  gitVersion: "devel"
  playbook: "demo/project/test.yml"
  sshSharedSecretName: "azimuth-sshkey"
  sshSharedSecretNamespace: "azimuth-caas"
  extraVars:
    foo: "bar"
    test_int: 5
    test_dict:
      something: false
    test_bool: true
