---
apiVersion: caas.azimuth.stackhpc.com/v1alpha1
kind: ClusterType
metadata:
  name: "quick-test"
spec:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-caas-operator/578d0ab845770123d06094ebec44ba99375858dc/tools/ui_meta_quick_test.yaml"
  gitUrl: "https://github.com/ansible/ansible-runner"
  gitVersion: "devel"
  playbook: "demo/project/test.yml"
  extraVars:
    foo: "bar"
    test_int: 5
    test_dict:
      something: false
    test_bool: true
