name: on push to main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  unit_tests:
    uses: ./.github/workflows/tox.yaml
    with:
      ref: ${{ github.ref }}

  publish_images:
    uses: ./.github/workflows/publish-images.yaml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  publish_charts:
    needs: [publish_images]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  functional_tests:
    needs: [publish_images]
    uses: ./.github/workflows/functional.yaml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
