name: on push to main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  unit_tests:
    uses: ./.github/workflows/tox.yaml

  publish_artefacts:
    uses: ./.github/workflows/publish-artefacts.yaml

  functional_tests:
    needs: [publish_artefacts]
    uses: ./.github/workflows/functional.yaml
