name: PR publish (internal only)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Only run for PRs from branches of this repository (not external forks)
  # to prevent untrusted code from accessing repository secrets via pull_request_target.
  publish_images:
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/publish-images.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files

  publish_charts:
    needs: [publish_images]
    uses: ./.github/workflows/publish-charts.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write

  functional_tests:
    needs: [publish_images]
    uses: ./.github/workflows/functional.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

  # The integration tests require the charts, and are only worth running once
  # the functional tests are passing
  integration_tests:
    needs: [publish_charts, functional_tests]
    uses: ./.github/workflows/integration.yaml
    with:
      chart-version: ${{ needs.publish_charts.outputs.chart-version }}
    secrets: inherit
