name: on pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - edited
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Run the unit tests on every PR, even from external repos
  unit_tests:
    uses: ./.github/workflows/tox.yaml

  # When the PR is from a branch of the main repo, publish images and charts
  publish_images:
    uses: ./.github/workflows/publish-images.yaml
    if: github.repository == 'azimuth-cloud/azimuth-caas-operator'

  publish_charts:
    needs: [publish_images]
    uses: ./.github/workflows/publish-charts.yaml
    if: github.repository == 'azimuth-cloud/azimuth-caas-operator'

  # The functional tests require the runner image, so we can only run them
  # once the image has been built, and on PRs from the main repo
  functional_tests:
    needs: [publish_images]
    uses: ./.github/workflows/functional.yaml
    if: github.repository == 'azimuth-cloud/azimuth-caas-operator'

  # The integration tests require the charts, and are only worth running once
  # the functional tests are passing
  integration_tests:
    needs: [publish_charts, functional_tests]
    uses: ./.github/workflows/integration.yaml
    with:
      chart-version: ${{ needs.publish_charts.outputs.chart-version }}
    secrets: inherit
    if: github.repository == 'azimuth-cloud/azimuth-caas-operator'
