name: Publish images

on:
  workflow_call:

jobs:
  build_push_operator_image:
    name: Build and push operator image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/azimuth-cloud/azimuth-caas-operator
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: azimuth-cloud/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: azimuth-caas-operator
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_push_ansible_runner_image:
    name: Build and push ansible runner image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write         # needed for signing the images with GitHub OIDC Token
      packages: write         # required for pushing container images
      security-events: write  # required for pushing SARIF files
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ansible-builder
        run: python -m pip install ansible-builder

      - name: Generate Docker build context from EE spec
        run: |
          ansible-builder create \
            --file ./execution-environment/execution-environment.yml \
            --context ./ee-context \
            --output-filename Dockerfile

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/azimuth-cloud/azimuth-caas-operator-ee
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: azimuth-cloud/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: azimuth-caas-operator-ee
          context: ./ee-context/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  mirror_ara_image:
    name: Mirror and tag the latest ARA image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install skopeo
        run: sudo apt-get -y update && sudo apt-get install -y skopeo

      - name: Mirror ARA image
        run: |-
          skopeo copy \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker://quay.io/recordsansible/ara-api:latest \
            docker://ghcr.io/azimuth-cloud/ara-api:${GITHUB_SHA::7}
