name: Publish operator
# Run the tasks on every push that changes either the operator image or chart
on:
  push:
    # Note that the paths filter is not evaluated for tags, so this should run for
    # every push to a branch that changes the operator and every tag
    branches: ['**']
    tags: ['**']
jobs:
  build_push_operator_image:
    name: Build and push operator image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker layer caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-operator-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-operator-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stackhpc/azimuth-caas-operator
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # https://github.com/docker/buildx/pull/535
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  publish_charts:
    name: Publish Helm charts to GitHub pages
    runs-on: ubuntu-latest
    # We need the image to have been built (if required) and tagged before publishing charts
    needs: build_push_operator_image
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          # This is important for "git rev-list --count" to work correctly when
          # determining the number of commits since the last tag
          fetch-depth: 0

      # Use an up-to-date version of Python for the script
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # This action packages and pushes the chart
      - name: Publish charts
        run: ./.github/workflows/publish-chart.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
