name: Publish charts

on:
  workflow_call:
    outputs:
      chart-version:
        description: The chart version that was published
        value: ${{ jobs.publish_charts.outputs.chart-version }}

jobs:
  publish_charts:
    name: Publish Helm charts to GitHub pages
    runs-on: ubuntu-latest
    outputs:
      chart-version: ${{ steps.semver.outputs.version }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          # This is important for the semver action to work correctly
          # when determining the number of commits since the last tag
          fetch-depth: 0

      - name: Get SemVer version for current commit
        id: semver
        uses: azimuth-cloud/github-actions/semver@master

      - name: Publish Helm charts
        uses: azimuth-cloud/github-actions/helm-publish@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.semver.outputs.version }}
          app-version: ${{ steps.semver.outputs.short-sha }}
